export const presentHeader = ["닉네임", "토큰갯수", "한줄 메세지", "날짜"];

export const presentData = [
  {
    nickname: "닉네임",
    token: 9,
    comment: "우끼?",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "롯데시식코트",
    token: 3667,
    comment: "침대콜링",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "저예요",
    token: 443,
    comment: "먹고떨어져",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "쓱쓲쓱쓱",
    token: 312,
    comment: "저는야구를몰라요",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오오",
    token: 312,
    comment: "ㅇ로ㅓ아ㅓ러",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "김미영",
    token: 312,
    comment: "스팸메세지",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "임그래",
    token: 312,
    comment: "고양이",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "이정현",
    token: 6,
    comment: "소노스터디카페거너스",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "잠만보",
    token: 3112142,
    comment: "거다이맥스잠만보",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
  {
    nickname: "오은영박사",
    token: 1,
    comment: "울지말고말해봐",
    takeDate: "2023.12.01",
    teamName: "한화 이글스",
  },
];
export const pageDummyData = {
  code: 200,
  message: "정상적으로 처리되었습니다.",
  data: {
    content: presentData,
    pageable: {
      pageNumber: 1,
      pageSize: 10,
      sort: {
        sorted: false,
        empty: true,
        unsorted: true,
      },
      offset: 10,
      paged: true,
      unpaged: false,
    },
    totalElements: 1,
    totalPages: 1,
    last: true,
    size: 10,
    number: 1,
    sort: {
      sorted: false,
      empty: true,
      unsorted: true,
    },
    numberOfElements: 0,
    first: false,
    empty: true,
  },
};
